const http = require('http');
const crypto = require('crypto');

const PORT = Number(process.env.PROMPT_CREATOR_PORT || 4174);
const OLLAMA_URL = process.env.OLLAMA_URL || 'http://127.0.0.1:11434/api/chat';
const MODEL = process.env.PROMPT_CREATOR_MODEL || 'qwen3:8b';
const sessions = new Map();

function json(res,status,body){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(body));}
function html(res,body){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});res.end(body);}
function readBody(req){return new Promise((resolve,reject)=>{let data='';req.on('data',c=>{data+=c;if(data.length>100000)reject(new Error('Request too large'));});req.on('end',()=>{try{resolve(data?JSON.parse(data):{})}catch{reject(new Error('Invalid JSON'))}});req.on('error',reject);});}
function normalizeMode(mode){return mode==='show-me-how'?'show-me-how':'just-do-it';}
function systemPrompt(mode){const rules=mode==='show-me-how'?`SHOW ME HOW MODE:\n- Work with the user one useful question at a time.\n- Ask only when the answer can materially improve the final prompt.\n- Never ask for facts the AI could reasonably research, infer safely, or look up later.\n- Do not ask multiple questions in one turn.\n- Stop asking as soon as enough is known.`:`JUST DO IT MODE:\n- Do as much of the work as possible without interrupting the user.\n- Infer harmless details when reasonable and record them as assumptions.\n- Identify facts that should be researched later instead of asking the user to know them.\n- Ask only when personal input is truly required.\n- Prefer producing the finished prompt immediately.`;return `You are Prompt Creator. The user supplies intent; you discover requirements, identify what should be researched, and create a strong executable prompt.\n\n${rules}\n\nReturn ONLY valid JSON: {"action":"question"|"prompt","question":"","prompt":"","assumptions":[],"research":[],"reason":""}. Do not invent precise facts that should instead be researched.`;}
async function callOllama(messages,mode){const r=await fetch(OLLAMA_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:MODEL,stream:false,format:'json',messages:[{role:'system',content:systemPrompt(mode)},...messages]})});if(!r.ok)throw new Error(`Ollama returned ${r.status}`);const data=await r.json();let p;try{p=JSON.parse(data?.message?.content||'')}catch{throw new Error('Model did not return valid JSON')}if(!['question','prompt'].includes(p.action))throw new Error('Model returned invalid action');return {action:p.action,question:typeof p.question==='string'?p.question.trim():'',prompt:typeof p.prompt==='string'?p.prompt.trim():'',assumptions:Array.isArray(p.assumptions)?p.assumptions.map(String):[],research:Array.isArray(p.research)?p.research.map(String):[],reason:typeof p.reason==='string'?p.reason.trim():''};}
function makeSession(mode,request){const s={id:crypto.randomUUID(),mode:normalizeMode(mode),request:String(request||'').trim(),messages:[],turns:0,createdAt:Date.now()};sessions.set(s.id,s);return s;}
async function advance(s,userText){if(s.turns>=12)s.messages.push({role:'user',content:'Stop asking questions. Create the best finished prompt now and clearly mark assumptions or research needs.'});else if(userText)s.messages.push({role:'user',content:userText});s.turns++;const result=await callOllama(s.messages,s.mode);if(result.action==='question'){if(!result.question)throw new Error('Question action contained no question');s.messages.push({role:'assistant',content:result.question});}else{if(!result.prompt)throw new Error('Prompt action contained no prompt');s.messages.push({role:'assistant',content:result.prompt});}return result;}

const PAGE=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Prompt Creator</title><style>
:root{font-family:Arial,Helvetica,sans-serif;color:#202124;background:#f6f7f8}*{box-sizing:border-box}body{margin:0}.wrap{max-width:850px;margin:0 auto;padding:24px}.card{background:#fff;border:1px solid #ddd;border-radius:14px;padding:22px;box-shadow:0 2px 8px rgba(0,0,0,.05)}h1{margin:0 0 8px}.sub{margin:0 0 20px;color:#555}.top{display:flex;justify-content:space-between;align-items:center;gap:12px}.toggle{display:grid;grid-template-columns:1fr 1fr;border:1px solid #aaa;border-radius:10px;overflow:hidden}.toggle button{border:0;padding:11px 14px;background:#fff;color:#202124;cursor:pointer;font-weight:600}.toggle button+button{border-left:1px solid #aaa}.toggle button.active{background:#202124;color:#fff}.about{border:0;background:transparent;text-decoration:underline;cursor:pointer}.messages{margin:20px 0;min-height:150px}.msg{padding:12px 14px;border-radius:10px;margin:10px 0;white-space:pre-wrap}.user{background:#eef3ff}.ai{background:#f0f0f0}.prompt{background:#eef8ee;border:1px solid #b7d8b7}.row{display:flex;gap:8px}textarea{width:100%;min-height:90px;padding:12px;font:inherit;border:1px solid #aaa;border-radius:10px;resize:vertical}button.primary{padding:0 18px;border:0;border-radius:10px;background:#202124;color:#fff;cursor:pointer}.small{font-size:13px;color:#666;margin-top:8px}.meta{margin-top:12px;padding:12px;background:#fafafa;border-radius:8px;font-size:14px}dialog{max-width:650px;border:0;border-radius:14px;padding:0;box-shadow:0 10px 35px rgba(0,0,0,.25)}dialog .inside{padding:24px}.modebox{padding:12px;border:1px solid #ddd;border-radius:10px;margin:12px 0}
</style></head><body><div class="wrap"><div class="card"><div class="top"><div><h1>Prompt Creator</h1><p class="sub">Tell me what you want AI to help you accomplish.</p></div><button type="button" class="about" id="aboutBtn">About</button></div><div class="toggle"><button type="button" id="just" class="active">Just Do It</button><button type="button" id="show">Show Me How</button></div><div class="small" id="modeHelp">I’ll do as much as possible myself and interrupt only when I truly need your input.</div><div class="messages" id="messages"></div><div class="row"><textarea id="input" placeholder="What would you like AI to help you accomplish?"></textarea><button type="button" class="primary" id="send">Send</button></div><div class="small" id="status"></div></div></div>
<dialog id="about"><div class="inside"><h2>How Prompt Creator Works</h2><p>You don’t need to know how to write a great AI prompt. Tell Prompt Creator what you’re trying to accomplish. It figures out what the AI needs to know.</p><div class="modebox"><strong>Just Do It</strong><p>Prompt Creator does as much work as possible without unnecessary interruptions.</p></div><div class="modebox"><strong>Show Me How</strong><p>Prompt Creator asks one useful question at a time and helps you shape the request.</p></div><p><strong>You supply the intent. The AI discovers the requirements, identifies what should be researched, and helps produce the result.</strong></p><button type="button" id="closeAbout">Close</button></div></dialog>
<script>
let mode='just-do-it',sessionId=null,waiting=false;const input=document.getElementById('input'),messages=document.getElementById('messages'),status=document.getElementById('status'),just=document.getElementById('just'),show=document.getElementById('show'),modeHelp=document.getElementById('modeHelp');
function add(text,cls){const d=document.createElement('div');d.className='msg '+cls;d.textContent=text;messages.appendChild(d);}
function setMode(next){if(sessionId&&!confirm('Changing modes will start a new request. Continue?'))return;mode=next;sessionId=null;messages.innerHTML='';just.classList.toggle('active',mode==='just-do-it');show.classList.toggle('active',mode==='show-me-how');modeHelp.textContent=mode==='just-do-it'?`I’ll do as much as possible myself and interrupt only when I truly need your input.`:`I’ll ask one useful question at a time and help you shape the request.`;}
just.addEventListener('click',()=>setMode('just-do-it'));show.addEventListener('click',()=>setMode('show-me-how'));
async function send(){if(waiting)return;const text=input.value.trim();if(!text)return;waiting=true;status.textContent='Thinking…';input.value='';add(text,'user');try{const url=sessionId?'/api/answer':'/api/start';const body=sessionId?{id:sessionId,answer:text}:{mode,request:text};const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error||'Request failed');sessionId=data.id;if(data.action==='question')add(data.question,'ai');else{add(data.prompt,'prompt');let extra=[];if(data.assumptions?.length)extra.push('Assumptions:\n• '+data.assumptions.join('\n• '));if(data.research?.length)extra.push('Research/verify:\n• '+data.research.join('\n• '));if(extra.length)add(extra.join('\n\n'),'meta');sessionId=null;}status.textContent='';}catch(e){status.textContent='Error: '+e.message;}finally{waiting=false;}}
document.getElementById('send').addEventListener('click',send);input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}});const dlg=document.getElementById('about');document.getElementById('aboutBtn').addEventListener('click',()=>dlg.showModal());document.getElementById('closeAbout').addEventListener('click',()=>dlg.close());
</script></body></html>`;

const server=http.createServer(async(req,res)=>{try{if(req.method==='GET'&&req.url==='/')return html(res,PAGE);if(req.method==='GET'&&req.url==='/health')return json(res,200,{ok:true,model:MODEL,port:PORT});if(req.method==='POST'&&req.url==='/api/start'){const body=await readBody(req),request=String(body.request||'').trim();if(!request)return json(res,400,{error:'Tell me what you want AI to help you accomplish.'});const s=makeSession(body.mode,request);s.messages.push({role:'user',content:`My request: ${request}`});const result=await advance(s,'');return json(res,200,{id:s.id,mode:s.mode,...result});}if(req.method==='POST'&&req.url==='/api/answer'){const body=await readBody(req),s=sessions.get(String(body.id||''));if(!s)return json(res,404,{error:'That request has expired. Please start again.'});const answer=String(body.answer||'').trim();if(!answer)return json(res,400,{error:'Please answer the question or start again.'});const result=await advance(s,answer);if(result.action==='prompt')sessions.delete(s.id);return json(res,200,{id:s.id,mode:s.mode,...result});}json(res,404,{error:'Not found'});}catch(err){console.error(err);json(res,500,{error:err.message||'Unexpected error'});}});
if(require.main===module)server.listen(PORT,'127.0.0.1',()=>{console.log(`Prompt Creator running at http://127.0.0.1:${PORT}`);console.log(`Model: ${MODEL}`);});
module.exports={normalizeMode,systemPrompt,makeSession};
